### ISSUE TITLE
syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) 

### ISSUE THREAD

**Issue by ghost** [nalingia/nova-simple-toolbar-link#1]
First it did not like the ";" at the end of the (new SimpleToolbarLink) declaration

Also SimpleToolbarLink.php:11
`syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) `
 `protected ?string $name = null;`

Not sure if this causes any issues but this worked for me.
` protected $name = null;`
` protected $href = null;`

**Comment by nalingia** [comment]
Hi @dmgdwd,
could you share  PHP version you are working with?

**Comment by nalingia** [comment]
The issue has been fixed in version 1.0.2.

**Comment by ghost** [comment]
php version 7.3.2
